Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rockylinux9_vm"
    vb.cpus = 2
    vb.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y update
    sudo dnf -y install vim git curl
  SHELL
end
